### ISSUE TITLE
Reorder yield of GeneAssociation and Variation

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-ingest#103]
Current order for disassembled entities:

- Gene
- GeneAssociation
- Variation
- Trait
- TraitSet
- Submitter
- Submission
- ClinicalAssertion
- VariationArchive

Technically if reading the stream of objects from the `read_clinvar_xml` function, you will get a GeneAssociation that references a Variation which you've not received yet. We can reorder the yields from Variation.disassemble to return the self Variation before the GeneAssociation. Not sure how important this is. We're not using the `read_clinvar_xml` to actually create a coherent stream of objects and foreign keys, just to stream objects into separate files, where the inter and intra file object ordering doesn't matter at all.

**Comment by larrybabb** [comment]
@theferrit32 if this is not too disruptive (>2 or 3 hours) to do then please go ahead (otherwise push it to after all connect work is done). Let me know if we should discuss, but it makes sense to have the order fixed to support the original dependency goals.

**Comment by theferrit32** [comment]
Done in #113
