### ISSUE TITLE
Fix ClinGen ingest clinical_assertion_trait_set table fields in parser

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#155]
clinical_assertion_trait_set table fields that are missing or wrong:
	• clinical_assertion_trait_ids different
	• id appears different

**Comment by theferrit32** [comment]
We match the `clinical_assertion_trait` to `trait` (in `clinical_assertion_trait.trait_id`). The function that does this is `ClinicalAssertionTrait.find_matching_trait`. We need to add a step to take the set of normalized trait_id values and try to find a normalized `trait_set` which contains the same set of trait ids, and set `clinical_assertion.trait_set_id` to be that `trait_set.id`. A good place to put this would be `ClinicalAssertionTraitSet.find_matching_trait_set`.
