### ISSUE TITLE
ClinVar ingest not processing Genotypes properly

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#182]
ClinGen's version of the ClinVar ingest is not processing all of the component parts of some Genotypes, particularly those that contain Haplotypes and SimpleAlleles.

The _clinical_assertion_variation_ table is discrepant between the Clingen (clingen-dev.clinvar_2024_06_11_terry)and DSP (clingen-dev.clinvar_2024_06_11_v1_6_62) ingests. The following _clinical_assertion_variation_ records appear in the DSP tables but not ClinGen's:
[{
  "id": "SCV000196710.2"
}, {
  "id": "SCV000196710.3"
}, {
  "id": "SCV000196710.4"
}, {
  "id": "SCV000256231.2"
}, {
  "id": "SCV000256231.3"
}, {
  "id": "SCV000256231.4"
}, {
  "id": "SCV000537826.2"
}, {
  "id": "SCV000537826.3"
}, {
  "id": "SCV000537826.4"
}, {
  "id": "SCV001653281.2"
}, {
  "id": "SCV001653281.3"
}, {
  "id": "SCV001653281.4"
}]

The output above was produced by this query:
> select b.id from `clingen-dev.clinvar_2024_06_11_v1_6_62.clinical_assertion_variation` b where b.id not in (SELECT a.id from `clingen-dev.clinvar_2024_06_11_terry.clinical_assertion_variation` a) order by b.id

The ClinGen ingest is only picking up two of the five SCV records and the child_ids and descendant_ids fields of the clinical_assertion_variation table do not appear to be correct.

**Comment by theferrit32** [comment]
Working on this now. I am seeing the same thing with these ids missing. But since these are synthetic ids generated during parsing, it could be that there's some mismatch between the way we're generating the ids for variants inside a genotype or haplotype

**Comment by theferrit32** [comment]
The problem is I'm not correctly handling heterogenous variant types inside a Genotype. 

Like the direct children of this Genotype is a Haplotype and a SimpleAllele. Current code expects only 1 type to be at each level.
```
Genotype
  Haplotype
    SimpleAllele
  SimpleAllele

```

**Comment by theferrit32** [comment]
Added test case specifically for this: https://github.com/clingen-data-model/clinvar-ingest/blob/issue-182-fix-variation-descendants/test/test_issue_182.py

And test variation file: https://github.com/clingen-data-model/clinvar-ingest/blob/issue-182-fix-variation-descendants/test/data/original-clinvar-variation-424711.xml
