### ISSUE TITLE
Create an RCV File workflow

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#187]
Create an RCV file workflow called 'clinvar-rcv-ingest' based on the clinvar-ingest code base.
clinvar-rcv-ftp-watcher will call into this worflow and pass the same info as it does, but for the rcv weekly file.

**Comment by theferrit32** [comment]
Based on discussion on 2024-06-25:

When an RCV or VCV ingest pipeline is finished, they should look for a corresponding VCV or RCV release on the same day or within 1 day of itself. If it finds one, it should run the linker script to link the SCVs to the RCV/TraitSets

**Comment by theferrit32** [comment]
Closed by #197
