### ISSUE TITLE
Add RCVs and VCVs so that there are some variants in the intersection

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-ingest#232]
Add to the `RCV*.xml` files in the `test/data/rcv` directory by including all RCVs which go with the VCVs. We will need to scan through the RCV-oriented XML file to pull out relevant records, and generate individual release files for each, and a combined file. Combining can either be done by copy-pasting manually or adapting this script to work for the RCV tags:
https://github.com/clingen-data-model/clinvar-ingest/blob/clinvar-new/test/data/combine.py

**Comment by theferrit32** [comment]
VCV ids from https://github.com/clingen-data-model/clinvar-ingest/tree/clinvar-new/test/data

@larrybabb 
```
VCV000000002
VCV000000010
VCV000000032
VCV000000051
VCV000004897
VCV000013961
VCV000040200
VCV000097006
VCV000177881
VCV000222476
VCV000375881
VCV000406155
VCV000424711
VCV000634266
VCV001264328
```

**Comment by larrybabb** [comment]
handed this off to Kyle. Received new sample set. all seems good so far.
