### ISSUE TITLE
Simplified clinvar-ingest V2 workflow step to process ClinVar XML into model JSON files

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#45]
Will  need a notification endpoint for notification that a ClinVar XML release is available in the GCP bucket for processing into model JSON files.

Then initiate the processing and copy the files into a staging bucket for loading into BigQuery. These may be separate workflow steps.

**Comment by theferrit32** [comment]
Closed by #62
