### ISSUE TITLE
Write success message at end of workflow run

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-ingest#85]
In production, a workflow will be triggered by the `clinvar-ftp-watcher`. The `clinvar-ftp-watcher` does not wait for the workflow to finish or later check the status of the workflow. The `clinvar-ftp-watcher` will always write the ftp file information to a kafka topic in addition to triggering the workflow with it.

We need some way to externally know, without digging into logs or inferring it from workflow run histories:

1. A `clinvar-ingest` workflow run was started (and what input it was started with)
2. A `clinvar-ingest` workflow run completed (and what input it was started with)
  a. the workflow completed successfully
  b. the workflow had an error. What inputs were used. And what was the python stacktrace.

Sending a message to a slack channel is the ideal alert mechanism.

**Comment by toneillbroad** [comment]
After discussion, we agree that the workflow needs to be in charge of steps 1 and 2 above. 

Step 1 should be easy as we can add a step to the very start of the workflow to call into a service method for sending a 'start' slack message. 

Step 2 can be handled through the workflow try/catch mechanism available on each step. We can send a success slack message as the last step of the workflow to cover issue 2a above.  And for issue 2b, we can send failure slack messages in the catch clause of any (perhaps all) steps in the workflow.

The 'clinvar_ftp_watcher' source code contains a (currently unused) 'slack.clj' module (originally written by 'tbl') that perhaps could be considered for inclusion in the 'clinvar_ingest' api service.
