### ISSUE TITLE
Fix parse workflow step memory leak

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#89]
While testing a full clinvar release file in the cllinvar-ingest workflow, the cloud run service failed a number of times due to insufficient memory.

The memory was initially configured at 512MB and progressed through 4GB, 8GB and 16GB. All failed.

There must be an issue where we are holding onto memory during parsing. Kyle said he thinks he has an idea that it might be during the XML parsing.

**Comment by theferrit32** [comment]
Closed by #90
